phrase:
  access_token: 4fb8e198a5f4d7a688124dce4a4bc127947cec9a8d9e0459b56314769b9d233e
  project_id: 84b4841a4b8bf1c00e991af3bc280b4d

  push:
    sources:
    - file: ./locales/en.json
      params:
        file_format: nested_json
        update_translations: false
        locale_id: YOUR_LOCALE_ID # the locale must exist remotely
  pull:
    targets:
    - file: ./locales/hi.json
    params:
        file_format: nested_json
        locale_id: YOUR_LOCALE_ID # the locale must exist remotely
