phrase:
  access_token: 4fb8e198a5f4d7a688124dce4a4bc127947cec9a8d9e0459b56314769b9d233e
  project_id: 84b4841a4b8bf1c00e991af3bc280b4d
  file_format: nested_json

  push:
    sources:
    - file: ./locales/**/one-ui.json
      params:
        file_format: nested_json
        update_translations: false
        locale_id: 1aef6821b636e2c42946620be82e2572 

  pull:
    targets:
    - file: ./locales/<locale_code>/one-ui.json
      params:
          file_format: nested_json
          locale_id: 5305703b79ca7d8109184d287c2dc641 

